apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: beszel
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet    
      containers:
        - name: beszel-agent
          image: henrygd/beszel-agent:0.12.0-beta2
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTEN
              value: "45876"
            - name: TOKEN
              value: "?"
            - name: KEY            
              value: "?"
            - name: HUB_URL
              value: "http://hub.beszel.svc.cluster.local:8090"
          ports:
            - containerPort: 45876
              name: http
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '0.5'
              memory: '512Mi'
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate