apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel-hub
  namespace: default
spec:
  selector:
    matchLabels:
      app: beszel-hub
  template:
    metadata:
      labels:
        app: beszel-hub
    spec:
      containers:
        - name: beszel-hub
          image: henrygd/beszel:0.11.1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8090
              name: http
          resources:
            requests:
              cpu: '0.5'
              memory: '512Mi'
            limits:
              cpu: '0.5'
              memory: '512Mi'
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: beszel-hub
  namespace: default
spec:
  type: NodePort
  selector:
    app: beszel-hub
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30001