apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel-hub
  namespace: beszel
spec:
  selector:
    matchLabels:
      app: beszel-hub
  template:
    metadata:
      labels:
        app: beszel-hub
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - worker-0
      containers:
        - name: beszel-hub
          image: henrygd/beszel:0.12.0-beta2
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8090
              name: port-8090
            - containerPort: 80
              name: webhook            
          resources:
            requests:
              cpu: '0.1'
              memory: '128Mi'
            limits:
              cpu: '0.5'
              memory: '512Mi'
          volumeMounts:
            - name: dados
              mountPath: /beszel_data
      restartPolicy: Always
      volumes:
      - name: dados
        hostPath:
          path: /beszel/beszel_data
---
apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: beszel
spec:
  type: NodePort
  selector:
    app: beszel-hub
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30001